### ISSUE TITLE
feature-request: Propose adding a setting to make runtime proto generation optional.

### ISSUE THREAD

**Issue by eric-peacock** [GuangTianLi/grpcalchemy#38]
For my particular use-case I'd like to be able to invoke poco generation at build and packaging, not at gRPC runtime.  Propose:

1. Adding a setting AUTO_GENERATE_POCOS (or similar) to settings with default to True (preserving current behavior), and;
2. providing a public API to invoke generation of pocos during the build.

Basically proposing to make the call to `generate_proto_file` in `server.run` optional. 

Happy to do the work and PR, but thought I'd raise here.

**Comment by GuangTianLi** [comment]
Done in 0.7.1.

**Comment by eric-peacock** [comment]
Thank you.
